--liquibase formatted sql
--changeset demintsev:20241002144934_create_common_tables
CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name_from_google VARCHAR,
  full_name_from_google VARCHAR,
  email_from_google VARCHAR,
  email VARCHAR(256) NOT NULL,
  role VARCHAR(16),
  password VARCHAR(256),
  provider VARCHAR(15)
);